import pandas as pd


def execute_python_code(
    code: str,
    data_file_path: str | None,
    downloaded_data_file_path: str | None,
) -> dict[str, str]:
    """
    Executes the provided Python code in a restricted context with access to the
    data files.

    :param code: The Python code to execute, which should generate a plot
    and/or save a dataframe.
    :param data_file_path: Path to the data file generated by the data extractor
    agent.
    :param downloaded_data_file_path: Path to the data file generated by the data
    downloader agent.
    :return: A dictionary containing the paths to the generated plot and dataframe
    or an error message if execution fails.
    """
    df = pd.read_csv(data_file_path) if data_file_path else None
    df_download = (
        pd.read_csv(downloaded_data_file_path) if downloaded_data_file_path else None
    )
    context = {
        "df": df,
        "df_download": df_download,
        "plot_path": "",
        "df_file_path": "",
    }

    try:
        exec(code, context)
        return {
            "plot_path": context["plot_path"],
            "df_file_path": context["df_file_path"],
            "error_message": None,
        }
    except Exception as e:
        return {
            "plot_path": None,
            "df_file_path": None,
            "error_message": str(e),
        }


def get_dataset_metadata(data_file_path: str | None) -> str:
    """
    Build a string containing metadata about the dataset.

    param data_file_path: Path to the data file
    return: Formatted string of dataset metadata
    """
    if data_file_path is None:
        return ""

    df = pd.read_csv(data_file_path)

    # Basic info
    info_lines = [
        f"DATASET INFOS for file {data_file_path}:",
        f"Shape: {df.shape[0]} rows x {df.shape[1]} columns",
        "Columns and types:",
    ]

    for col, dtype in df.dtypes.items():
        info_lines.append(f"  - {col}: {dtype}")

    # Missing values
    missing = df.isnull().sum()
    info_lines.append("Missing values per column:")
    for col, miss in missing.items():
        info_lines.append(f"  - {col}: {miss}")

    # Basic statistics for numeric columns
    numeric_cols = df.select_dtypes(include="number").columns
    if len(numeric_cols) > 0:
        info_lines.append("\nBasic statistics for numeric columns:")
        stats = df[numeric_cols].describe()
        info_lines.append(stats.to_string())

    # Include head and optionally tail
    info_lines.append("\nFirst rows:")
    info_lines.append(df.head().to_string(index=False))
    info_lines.append("\nLast rows:")
    info_lines.append(df.tail().to_string(index=False))

    return "\n".join(info_lines)
